// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0tWws8HzwWmbO5kEGC20bEursCgAxSc',
    appId: '1:459351654272:web:b430861026f6e0bc99cb65',
    messagingSenderId: '459351654272',
    projectId: 'miniquora-eab5f',
    authDomain: 'miniquora-eab5f.firebaseapp.com',
    storageBucket: 'miniquora-eab5f.appspot.com',
    measurementId: 'G-NE752R2EGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWZuPSse2A_F3AjeBeZJNnoPXVqdFO2JY',
    appId: '1:459351654272:android:d2753739203df8fd99cb65',
    messagingSenderId: '459351654272',
    projectId: 'miniquora-eab5f',
    storageBucket: 'miniquora-eab5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXNHIU-XdObldulyExRzwK4EIlcrNQ9YQ',
    appId: '1:459351654272:ios:f01b097363c7061899cb65',
    messagingSenderId: '459351654272',
    projectId: 'miniquora-eab5f',
    storageBucket: 'miniquora-eab5f.appspot.com',
    iosBundleId: 'com.example.miniquora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXNHIU-XdObldulyExRzwK4EIlcrNQ9YQ',
    appId: '1:459351654272:ios:f01b097363c7061899cb65',
    messagingSenderId: '459351654272',
    projectId: 'miniquora-eab5f',
    storageBucket: 'miniquora-eab5f.appspot.com',
    iosBundleId: 'com.example.miniquora',
  );
}
